# Generated by Django 4.1.7 on 2023-02-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('tipologia', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('inversion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('mapa', models.CharField(max_length=255)),
            ],
        ),
    ]
