# Generated by Django 4.1.7 on 2023-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servEvalAmbient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='inversion',
            field=models.FloatField(),
        ),
    ]
