# Generated by Django 4.1.7 on 2023-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servEvalAmbient', '0004_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
